name: cars_ud
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.0-116.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^2.1.0
  # Firebase
  firebase_auth: ^3.0.1
  firebase_core: ^1.4.0
  cloud_firestore: ^3.1.1
  firebase_storage: ^10.2.0
  # Google Sign In
  google_sign_in: ^5.0.7
  # Provider
  provider: ^5.0.0
  # Image picker
  image_picker: ^0.8.4+4


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

